name: greenfoot
version: "3.9.0"
summary: Educational software designed to make learning programming easy and fun
description: |
  Greenfoot teaches object orientation with Java. Create 'actors' which live in 'worlds' to build games, simulations, and other graphical programs.
base: core22
confinement: strict
architectures: [amd64]

apps:
  greenfoot:
    extensions:
      - gnome
    command: usr/bin/greenfoot
    common-id: org.greenfoot.Greenfoot
    plugs:
      - home
      - network
      - network-bind
  bluej:
    extensions:
      - gnome
    command: usr/bin/greenfoot-bluej
    plugs:
      - home
      - network
      - network-bind

parts:
  greenfoot:
    plugin: dump
    source: https://www.greenfoot.org/download/files/Greenfoot-linux-x64-390.deb
    source-type: deb
    override-build: |
      cp -r usr $SNAPCRAFT_PART_INSTALL 
      sed -i 's/\/usr/$SNAP\/usr/g' $SNAPCRAFT_PART_INSTALL/usr/bin/greenfoot
      sed -i "s/java\"/java\" -Duser.home=\$HOME/g" $SNAPCRAFT_PART_INSTALL/usr/bin/greenfoot
      cp $SNAPCRAFT_PART_INSTALL/usr/bin/greenfoot $SNAPCRAFT_PART_INSTALL/usr/bin/greenfoot-bluej
      sed -i "s/greenfoot=true/greenfoot=false/g" $SNAPCRAFT_PART_INSTALL/usr/bin/greenfoot-bluej
    override-prime: |
      snapcraftctl prime
